CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  nickname VARCHAR(255) NOT NULL UNIQUE,
  hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS books(
  id SERIAL PRIMARY KEY,
  isbn VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews(
  user_id INTEGER REFERENCES users(id),
  book_id INTEGER REFERENCES books(id),
  rating INTEGER NOT NULL,
  text VARCHAR(1023) NOT NULL,
  PRIMARY KEY (user_id, book_id)
);